# Generated by Django 3.2.4 on 2021-06-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaXServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='atencionxservicio',
            name='ate',
        ),
        migrations.RemoveField(
            model_name='atencionxservicio',
            name='ser',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pac_per',
        ),
        migrations.RemoveField(
            model_name='reservaxatencion',
            name='ate',
        ),
        migrations.RemoveField(
            model_name='reservaxatencion',
            name='res',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='res_atenciones',
        ),
        migrations.AddField(
            model_name='reserva',
            name='res_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enfermeriaapp.persona'),
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='AtencionXServicio',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='ReservaXAtencion',
        ),
        migrations.AddField(
            model_name='reservaxservicio',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermeriaapp.reserva'),
        ),
        migrations.AddField(
            model_name='reservaxservicio',
            name='ser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermeriaapp.servicio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='res_servicios',
            field=models.ManyToManyField(through='enfermeriaapp.ReservaXServicio', to='enfermeriaapp.Servicio'),
        ),
    ]
