# Generated by Django 3.2.4 on 2021-06-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0003_tranresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaxservicio',
            name='cant',
            field=models.IntegerField(null=True),
        ),
    ]
