# Generated by Django 3.2.4 on 2021-06-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0004_reservaxservicio_cant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_enfermero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enfermeriaapp.enfermero'),
        ),
    ]
